[env:esp32-c6-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv
board_upload.flash_size = 8MB
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
lib_deps =
    moononournation/GFX Library for Arduino@^1.4.9
    bblanchon/ArduinoJson@^7.0.4
